# Generated by Django 4.2.15 on 2024-08-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("picture", models.ImageField(upload_to="")),
                ("ingredients", models.JSONField()),
                ("instructions", models.JSONField()),
                ("tags", models.JSONField()),
                ("notes", models.TextField()),
            ],
        ),
    ]
