# Generated by Django 4.2.15 on 2024-08-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0002_ingredient_instruction_tag_remove_recipe_ingredients_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="picture",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
