# Generated by Django 4.2.15 on 2024-08-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="instructions",
        ),
        migrations.DeleteModel(
            name="Instruction",
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(blank=True),
        ),
    ]
