# Generated by Django 4.2.15 on 2024-09-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_remove_recipe_instructions_delete_instruction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipe", to="recipes.ingredient"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(related_name="recipe", to="recipes.tag"),
        ),
    ]
