# Generated by Django 4.2.15 on 2024-09-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_recipe_ingredients_alter_recipe_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["tag"]},
        ),
        migrations.AlterField(
            model_name="recipe",
            name="picture",
            field=models.ImageField(blank=True, upload_to="photo_recipes/"),
        ),
    ]
