# Generated by Django 4.2.15 on 2024-09-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_ingredient_options_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="picture",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
