# Generated by Django 4.2.15 on 2024-09-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_alter_recipe_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="picture",
            field=models.ImageField(blank=True, upload_to="photo_recipes/"),
        ),
    ]
