# Generated by Django 4.2.15 on 2024-09-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_alter_recipe_instructions_alter_recipe_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="recipe", to="recipes.tag"
            ),
        ),
    ]
